### PR TITLE
Beta 0.1

### PR DESCRIPTION
**Pull request by leonardas103**
first

### CODE REVIEW

**Comment by Matt1994** [comment]
First things first:

What is the difference between index.html and index-2.html?

**Comment by Theys96** [comment]
It seems the problem on htmlpreview.github.io is that it can't find jQuery via the google link. I suggest using the jQuery version in the repository anyway.
This means putting the jQuery file in the /js/lib directory and updating the pages accordingly.

**Comment by Matt1994** [comment]
I've fixed the links on the pages. Just needed the https:// in front of the link

**Comment by leonardas103** [comment]
I changed the view link in the readme so that it works after the merge. The index.htm and index2.htm are the same, index2 being for the Home button. I'm guessing Home be different from the Main Page later on.

**Comment by Matt1994** [comment]
Home will be the main landing of the website, which will contain some general information about the product.

Thijs, what was the reason for creating index and index-2? Did you create index-2?

**Comment by Theys96** [comment]
@Matt1994 No, I didn't.

**Comment by Matt1994** [comment]
Weird. I will remove index.html and rename index-2 to index. Doesn't appear to be any differences but just want to be safe.

**Comment by Theys96** [comment]
I get what Leonardas means though. However I'd say we'll cross that bridge when we get there.
He means the landing page and "Home" may be different pages in the future.
Also, we should name the pages with useful names. Index.html is default, not much we can do about that yet, but let's be descriptive for the rest of the pages.

**Review by Theys96 — COMMENTED** [review]
Good job.
However, I still think having a local jQuery installation is preferable.

**Review by Matt1994 — APPROVED** [review]
Everything now looks good. I'm happy to merge.

**Pull request merged**
