### PR TITLE
Beta 0.1

### PR DESCRIPTION
**Pull request by Theys96**
As said before, this thing seems pretty ready.

### CODE REVIEW

**Comment by Matt1994** [comment]
Only thing I can think of needing to be changed is the text on the card and document creation, since it still says about them being offline demos. I think Peter mentioned what kind of things it should say here, so it may be a good idea to look at the comments he left on the requirements doc and change them.

**Comment by Theys96** [comment]
Sure let's have a look at that

**Comment by Theys96** [comment]
Done

**Review by Matt1994 — APPROVED** [review]
Looks good now

**Pull request merged**
