### PR TITLE
Profile

### PR DESCRIPTION
**Pull request by Theys96**
The creator shift is pretty much done on client side now, and this branch is becoming pretty massive.
Saving settings is done on client-side and only needs to be made functional on server-side once the new user model is implemented.

### CODE REVIEW

**Comment by Matt1994** [comment]
We should wait for Martin to accept the Iteration 2.1 pull request before this one

**Comment by Theys96** [comment]
Alright we'll leave it open until then. In the meanwhile we can perfect this branch.

**Comment by Matt1994** [comment]
Since Martin has now accepted the other request, I'll review and merge this

**Review by Matt1994 — APPROVED** [review]
Looking good.

**Pull request merged**
